Add support for Samsung browsers
art19/useragent pull request #29
Opened 2021-06-16 17:30 UTC by julian-lai

Currently, `UserAgent` reports Samsung browsers as Chrome.

2021-06-16 18:17 UTC, ziggythehamster requested changes
Thanks for the contribution! I'll see if I can find more UAs to test.

2021-06-16 18:17 UTC, ziggythehamster commented on lib/user_agent/browsers/samsung.rb
> +        agent.detect { |useragent| useragent.product == SAMSUNG_BROWSER}
```suggestion
        agent.detect { |useragent| useragent.product == SAMSUNG_BROWSER }
```

2021-06-16 18:17 UTC, ziggythehamster commented on lib/user_agent/browsers/samsung.rb
> +        self.detect { |useragent| useragent.product == SAMSUNG_BROWSER}.version
```suggestion
        self.detect { |useragent| useragent.product == SAMSUNG_BROWSER }.version
```

2021-06-16 18:17 UTC, ziggythehamster commented on lib/user_agent/browsers/samsung.rb
> +        SAMSUNG_BROWSER
```suggestion
        'Samsung Internet Browser'
```

This seems to be the name that Samsung prefers (according to here: https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser)

2021-06-16 18:17 UTC, ziggythehamster commented on lib/user_agent/browsers/samsung.rb
> +
```suggestion
    class Samsung < WebKit
```

2021-06-16 18:17 UTC, ziggythehamster commented on lib/user_agent/browsers/samsung.rb
> +      end
```suggestion
```

`WebKit` will auto-fill these correctly (i.e., `os` will be `Android 11` in your spec)

2021-06-16 18:17 UTC, ziggythehamster commented on spec/browsers/samsung_user_agent_spec.rb
> +end
```suggestion
end

```

For reasons I don't entirely understand, Git patches don't apply cleanly in some situations when there's not a newline at the end of the file. :)

2021-06-16 18:17 UTC, ziggythehamster commented on spec/browsers/samsung_user_agent_spec.rb
> +    expect(useragent.os).to eq('Android')
```suggestion
    expect(useragent.os).to eq(os)
```

2021-06-16 18:17 UTC, ziggythehamster commented on spec/browsers/samsung_user_agent_spec.rb
> +    expect(useragent.platform).to eq('Android')
```suggestion
    expect(useragent.platform).to eq(platform)
```

2021-06-16 18:17 UTC, ziggythehamster commented on spec/browsers/samsung_user_agent_spec.rb
> +    expect(useragent.browser).to eq('SamsungBrowser')
```suggestion
    expect(useragent.browser).to eq('Samsung Internet Browser')
```

2021-06-16 18:17 UTC, ziggythehamster commented on spec/browsers/samsung_user_agent_spec.rb
> +  it "returns 'Android' as its platform" do
```suggestion
  it "returns '#{platform}' as its platform" do
```

2021-06-16 18:17 UTC, ziggythehamster commented on spec/browsers/samsung_user_agent_spec.rb
> +  it "returns 'Android' as its operating system" do
```suggestion
  it "returns '#{os}' as its operating system" do
```

2021-06-16 18:17 UTC, ziggythehamster commented on spec/browsers/samsung_user_agent_spec.rb
> +describe "UserAgent: Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-G991B) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/11.1 Chrome/75.0.3770.143 Mobile Safari/537.36" do
Do you have any other UAs you can add to the spec? I'll see if I have any I can give you

2021-06-16 18:17 UTC, ziggythehamster commented on spec/browsers/samsung_user_agent_spec.rb
> +  it_behaves_like 'SamsungBrowser', '11.1', 'Android', 'Android'
```suggestion
  it_behaves_like 'SamsungBrowser', '11.1', 'Android', 'Android 11'
```

2021-06-16 18:27 UTC, ziggythehamster commented
Here's some more user agents to add to your spec:

```
Dalvik/2.1.0 (Linux; U; Android 10; SM-N975U Build/QP1A.190711.020) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/4.0 Chrome/44.0.2403.133 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 10; 9032Z) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/13.2 Chrome/83.0.4103.106 Mobile Safari/537.36
Firefox/5.0 (Linux; Android 5.0.1; SAMSUNG GT-I9505 Build/LRX22C) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/2.1 Chrome/34.0.1847.76 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 10.0; SAMSUNG SM-G960U Build/QP1A.190711.020) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/5.2 Chrome/51.0.2704.106 Mobile VR Safari/537.36
Mozilla/5.0 (Linux; Android 4.4.4; SAMSUNG SM-G318H/G318HJVS0AQC2 Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/2.0 Chrome/34.0.1847.76 Mobile Safari/537.36
```

That Firefox one is funny, because it's obviously still Chrome/WebKit based, they just decided to spoof the user-agent in one version.

2021-06-21 20:14 UTC, julian-lai commented
Hey @ziggythehamster, thank you for all the feedback and the additional UA examples! I've applied to changes to my PR :)

2021-06-24 19:01 UTC, ziggythehamster approved these changes

2021-06-30 21:38 UTC, merged