AROR-338 Support Facebook app
art19/useragent pull request #3
Opened 2018-05-16 23:03 UTC by skwongr

2018-05-16 23:09 UTC, ziggythehamster approved these changes

2018-05-30 16:11 UTC, johvet requested changes

2018-05-30 16:11 UTC, johvet commented on lib/user_agent/browsers/facebook.rb
> +        self.to_s[/.*FBAV\/([^;]*)/, 1]
use constants for the regex and in specs use let instead of ivar

2018-05-30 21:53 UTC, johvet approved these changes

2018-05-30 22:49 UTC, merged