AROR-341 Support Android Stagefright library
art19/useragent pull request #4
Opened 2018-05-17 17:35 UTC by skwongr

2018-05-17 18:23 UTC, ziggythehamster requested changes

2018-05-17 18:23 UTC, ziggythehamster commented on lib/user_agent/browsers/stagefright.rb
> +    # stagefright/1.2 (Linux;Android 5.0.1)
Also test these:

```
AlcatelOneTouch-Alcatel_5044R-SVN/02; stagefright/1.2 (Linux;Android 7.0)
Alcatel_5056O-SVN/07; stagefright/1.2 (Linux;Android 5.1.1)
BLADE L111-stagefright/1.2 (Linux;Android 5.1)
Fire OS/5.1.1 stagefright/1.2 (Linux;Android 5.1.1) ,Dalvik/2.1.0 (Linux; U; Android 5.1.1; KFFOWI Build/LMY47O)
Fire OS/6.0 stagefright/1.2 (Linux;Android 7.1.2)
Samsung SM-G925T stagefright/Beyonce/1.1.9 (Linux;Android 7.0)
stagefright/1.2 (Linux;Android 5.0 Huawei HUAWEI GRA-L09 GRA-L09V100R001C150B134)
stagefright/1.2 (Linux;Android 4.0.3) Mozilla/5.0(iPad; U; CPU iPhone OS 3_2 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Version/4.0.4 Mobile/7B314 Safari/531.21.10
```

2018-05-17 18:23 UTC, ziggythehamster commented on lib/user_agent/browsers/stagefright.rb
> +        'Stagefright'
This should be `Samsung Stagefright` if the version starts with `Beyonce/`. Or maybe it should be `Stagefright/Beyonce` or `Stagefright (Samsung)`? 

For the LG player, it matches because it has "stagefright alternative" in the name. For that player, choose either `NexPlayer` or `LG Player` depending on what's in the UA, and be sure to use the correct version. Here are some LG user agents:

```
LG-E615f/LG-E615f-V10p-SEP-02-2013 Player/NexPlayer 4.0 for Android (stagefright alternative) ,Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1667.0 Safari/537.36
LG-M250/V10o Player/LG Player 1.0 for Android 7.0 (stagefright alternative)
LG-D802/Desperate Rom LP UX4 V4 Player/LG Player 1.0 for Android 5.0.2 (stagefright alternative)
LG-D851/V10rro.lge.swversion_shortdate=V10r_22-OCT-2014 Player/LG Player 1.0 for Android 4.4.2 (stagefright alternative)
LG-D858HK/V30a Player/LG Player 1.0 for Android 6.0 (stagefright alternative)
LG-H873/V15c Player/LG Player 1.0 for Android 7.0 (stagefright alternative)
LG-H955/V15c Player/LG Player 1.0 for Android 5.1.1 (stagefright alternative) BMID/E67AB269FB
```

2018-05-17 18:23 UTC, ziggythehamster commented on spec/browsers/stagefright_user_agent_spec.rb
> +    expect(@useragent.version).to eq('Beyonce/1.1.9')
I think this should be 1.1.9 and whatever we decide the browser should be handles the beyonce part

2018-05-17 18:26 UTC, ziggythehamster commented on lib/user_agent/browsers/stagefright.rb
> +        'Stagefright'
Here are some more NexPlayer UAs:

```
LG-E615/LG-E615-V10l-APR-19-2013 Player/NexPlayer 4.0 for Android (stagefright alternative)
LG-E615/V10g-APR-23-2013 Player/NexPlayer 4.0 for Android (stagefright alternative)
LG-E615f/LG-E615f-V10h-OCT-10-2012 Player/NexPlayer 4.0 for Android (stagefright alternative)
LG-Player/NexPlayer4.0 for Android(stagefright alternative)
```

I wish these phone vendors wouldn't fork stagefright and give it some stupid new name that doesn't follow the user agent convention.

2018-05-22 16:51 UTC, ziggythehamster approved these changes

2018-05-30 16:11 UTC, johvet requested changes

2018-05-30 16:11 UTC, johvet commented on lib/user_agent/browsers/stagefright.rb
> +        agent.detect { |useragent| useragent.product =~ /stagefright/ } || agent.to_s =~ /stagefright alternative/
use constants for the regex

2018-05-30 16:11 UTC, johvet commented on spec/browsers/stagefright_user_agent_spec.rb
> +    expect(@useragent.browser).to eq('Stagefright')
pefer a let over instance variable

2018-05-30 21:52 UTC, johvet approved these changes

2018-05-30 22:39 UTC, merged